- name: Get installed PostgreSQL major version
  shell: "psql -V | awk '{print $3}' | cut -d '.' -f1"
  register: postgres_version
  changed_when: false

- name: Set PostgreSQL configuration directory dynamically
  set_fact:
    postgres_conf_dir: "/etc/postgresql/{{ postgres_version.stdout }}/main"

- name: Ensure PostgreSQL configuration directory exists
  file:
    path: "{{ postgres_conf_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0755

- name: Template PostgreSQL configuration
  template:
    src: postgresql.conf.j2
    dest: "{{ postgres_conf_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: Restart PostgreSQL

- name: Create PostgreSQL admin user
  postgresql_user:
    name: "{{ postgres_admin_user }}"
    password: "{{ postgres_admin_password }}"
    role_attr_flags: "SUPERUSER,CREATEDB,CREATEROLE"
    state: present
  become: true
  become_user: postgres
